# Generated by Django 3.1.7 on 2021-04-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_orderd',
        ),
    ]
