# Generated by Django 3.1.7 on 2021-03-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210326_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('size', models.CharField(blank=True, choices=[('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('X-LARGE', 'XL')], max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='shirt',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='size',
            field=models.CharField(blank=True, choices=[('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('X-LARGE', 'XL')], max_length=7),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.CharField(blank=True, choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=7),
        ),
    ]
