# Generated by Django 3.1.7 on 2021-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='shirt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
